-- ============================================================
-- ElectricScouts: Provider Seed Data
-- Comprehensive list of electricity providers across
-- all 12 deregulated U.S. states
-- ============================================================
-- NOTE: Run this AFTER migration 004_provider_enhancements.sql
-- This uses INSERT ... ON CONFLICT to be idempotent.
-- ============================================================

-- ─── TEXAS PROVIDERS ────────────────────────────────────────

INSERT INTO public.electricity_providers (name, slug, description, logo_url, website_url, affiliate_url, supported_states, offer_categories, rating, review_count, features, is_active, has_affiliate_program, phone)
VALUES
  ('TXU Energy', 'txu-energy', 'One of the largest and most recognized electricity providers in Texas, serving millions of residential and commercial customers since deregulation.', '/images/providers/txu-energy.png', 'https://www.txu.com', '', ARRAY['TX'], ARRAY['residential','business'], 4.2, 8500, ARRAY['Free nights & weekends','Bill credits','Solar buyback','No deposit options'], true, true, '1-800-818-6132'),
  ('Reliant Energy', 'reliant-energy', 'A leading Texas electricity provider offering innovative plans including free nights, weekends, and renewable energy options for homes and businesses.', '/images/providers/reliant-energy.png', 'https://www.reliant.com', '', ARRAY['TX'], ARRAY['residential','business','renewable'], 4.3, 9200, ARRAY['Free nights & weekends','Truly Free plans','Nest thermostat offers','Bill protection'], true, true, '1-866-222-7100'),
  ('Constellation Energy', 'constellation-energy', 'A national energy company providing electricity and natural gas across multiple deregulated states with competitive fixed and variable rate plans.', '/images/providers/constellation-energy.png', 'https://www.constellation.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA','CT'], ARRAY['residential','business','renewable'], 4.4, 6800, ARRAY['Price protection','Green energy options','Multi-state coverage','Business solutions'], true, true, '1-844-802-0498'),
  ('Gexa Energy', 'gexa-energy', 'Award-winning Texas electricity provider known for competitive rates, simple pricing, and excellent customer service ratings.', '', 'https://www.gexaenergy.com', '', ARRAY['TX'], ARRAY['residential','business'], 4.5, 5400, ARRAY['Simple pricing','No hidden fees','Competitive rates','Easy enrollment'], true, false, '1-866-961-9399'),
  ('Green Mountain Energy', 'green-mountain-energy', 'America''s longest-serving 100% renewable energy provider, offering clean electricity plans powered by wind and solar energy.', '/images/providers/green-mountain-energy.png', 'https://www.greenmountainenergy.com', '', ARRAY['TX','NY','PA','NJ','MD','MA','IL','OH'], ARRAY['residential','renewable'], 4.6, 4200, ARRAY['100% renewable energy','Carbon-free electricity','Solar buyback','Green rewards'], true, true, '1-866-785-4668'),
  ('Champion Energy', 'champion-energy', 'A competitive Texas electricity provider offering straightforward fixed-rate plans with no gimmicks and reliable customer service.', '/images/providers/champion-energy.png', 'https://www.championenergyservices.com', '', ARRAY['TX'], ARRAY['residential','business'], 4.1, 3800, ARRAY['Simple fixed rates','No deposit required','Quick enrollment','Reliable service'], true, false, '1-877-653-5090'),
  ('Frontier Utilities', 'frontier-utilities', 'Texas-based electricity provider offering competitive rates with a focus on customer satisfaction and transparent pricing.', '/images/providers/frontier-utilities.png', 'https://www.frontierutilities.com', '', ARRAY['TX'], ARRAY['residential','business'], 4.3, 3200, ARRAY['Competitive rates','No deposit plans','Bilingual support','Simple plans'], true, false, '1-866-926-8192'),
  ('Direct Energy', 'direct-energy', 'One of North America''s largest retail energy providers, now part of NRG Energy, serving residential and business customers across multiple states.', '/images/providers/direct-energy.png', 'https://www.directenergy.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA','CT'], ARRAY['residential','business','renewable'], 4.0, 7600, ARRAY['Free weekends','Connected home plans','Plenti rewards','Multi-state service'], true, true, '1-888-305-3828'),
  ('Ambit Energy', 'ambit-energy', 'Multi-state electricity provider offering competitive rates through a unique direct sales model with travel rewards for customers.', '/images/providers/ambit-energy.png', 'https://www.ambitenergy.com', '', ARRAY['TX','IL','NY','PA','NJ','MD','CT','OH'], ARRAY['residential','business'], 3.9, 4100, ARRAY['Travel rewards','Referral bonuses','Multi-state coverage','Simple plans'], true, false, '1-877-282-6248'),
  ('4Change Energy', '4change-energy', 'Texas electricity provider that donates a portion of every bill to charity, offering competitive rates with a social impact mission.', '', 'https://www.4changeenergy.com', '', ARRAY['TX'], ARRAY['residential'], 4.4, 2800, ARRAY['Charitable giving','Competitive rates','No deposit options','Simple enrollment'], true, false, '1-855-784-2426'),
  ('Payless Power', 'payless-power', 'Leading prepaid electricity provider in Texas, offering no-deposit, no-credit-check plans with daily billing and pay-as-you-go convenience.', '', 'https://www.paylesspower.com', '', ARRAY['TX'], ARRAY['residential'], 4.0, 5600, ARRAY['Prepaid plans','No credit check','No deposit','Daily billing'], true, false, '1-888-963-9363'),
  ('Cirro Energy', 'cirro-energy', 'Texas electricity provider offering a range of fixed and variable rate plans with straightforward pricing and reliable service.', '', 'https://www.cirroenergy.com', '', ARRAY['TX'], ARRAY['residential','business'], 3.8, 2400, ARRAY['Fixed rate plans','Variable options','Online management','Auto-pay discounts'], true, false, '1-800-692-4776'),
  ('Chariot Energy', 'chariot-energy', 'Texas solar energy provider offering 100% solar-powered electricity plans at competitive rates with a commitment to sustainability.', '', 'https://www.chariotenergy.com', '', ARRAY['TX'], ARRAY['residential','renewable'], 4.7, 1800, ARRAY['100% solar energy','Competitive rates','Solar buyback','No hidden fees'], true, false, '1-844-234-2746'),
  ('Pulse Power', 'pulse-power', 'Texas electricity provider offering simple, affordable plans with competitive rates and no hidden fees for residential customers.', '', 'https://www.pulsepower.com', '', ARRAY['TX'], ARRAY['residential'], 4.1, 1500, ARRAY['Simple plans','Competitive rates','No hidden fees','Easy signup'], true, false, '1-866-785-7312'),
  ('Discount Power', 'discount-power', 'Budget-friendly Texas electricity provider focused on delivering low rates with straightforward plans and no-frills service.', '', 'https://www.discountpowertx.com', '', ARRAY['TX'], ARRAY['residential','business'], 3.9, 2100, ARRAY['Low rates','Simple plans','Budget-friendly','No gimmicks'], true, false, '1-888-545-6160'),
  ('Rhythm Energy', 'rhythm-energy', 'Modern Texas electricity provider offering transparent pricing, time-of-use plans, and innovative energy management tools.', '', 'https://www.gotrhythm.com', '', ARRAY['TX'], ARRAY['residential','renewable'], 4.5, 1200, ARRAY['Time-of-use plans','Transparent pricing','App-based management','Renewable options'], true, true, '1-888-408-2836'),
  ('Octopus Energy', 'octopus-energy', 'Global renewable energy company now serving Texas with innovative green energy plans, smart tariffs, and cutting-edge technology.', '', 'https://octopusenergy.com', '', ARRAY['TX'], ARRAY['residential','renewable'], 4.6, 900, ARRAY['100% renewable','Smart tariffs','Innovative technology','Global brand'], true, false, ''),
  ('ENGIE', 'engie', 'Global energy company offering competitive electricity plans for residential and commercial customers across multiple deregulated states.', '', 'https://www.engie.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA'], ARRAY['residential','business','renewable'], 4.2, 3400, ARRAY['Multi-state coverage','Business solutions','Renewable options','Competitive rates'], true, false, '1-866-276-0356'),
  ('APG&E', 'apge', 'Multi-state retail electricity provider offering competitive fixed and variable rate plans for residential and commercial customers.', '', 'https://www.apge.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD'], ARRAY['residential','business'], 3.8, 2600, ARRAY['Multi-state coverage','Fixed rate plans','Business solutions','Online management'], true, false, '1-888-501-7243'),

-- ─── MULTI-STATE PROVIDERS ──────────────────────────────────

  ('Spark Energy', 'spark-energy', 'Multi-state retail electricity and natural gas provider serving residential and commercial customers with competitive rates and flexible plans.', '', 'https://www.sparkenergy.com', 'https://www.sparkenergy.com/partnership/affiliate/', ARRAY['TX','PA','OH','IL','NY','NJ','MD','MA','CT'], ARRAY['residential','business'], 3.7, 3100, ARRAY['Multi-state coverage','Affiliate program','Flexible plans','Natural gas options'], true, true, '1-877-547-7275'),
  ('Major Energy', 'major-energy', 'National retail energy provider serving residential and commercial customers across 10+ deregulated states with competitive fixed-rate plans.', '', 'https://majorenergy.com', '', ARRAY['CT','IL','MA','MD','ME','NJ','NY','OH','PA','RI','DE'], ARRAY['residential','business'], 3.6, 2800, ARRAY['Multi-state coverage','Fixed rate plans','No cancellation fees','Simple enrollment'], true, false, '1-888-625-6760'),
  ('Clearview Energy', 'clearview-energy', 'Multi-state electricity supplier offering competitive rates and renewable energy options across the Northeast and Midwest.', '', 'https://www.clearviewenergy.com', '', ARRAY['IL','OH','PA','NY','NJ','MD','MA','CT','RI','DE','ME'], ARRAY['residential','renewable'], 3.5, 1800, ARRAY['Multi-state coverage','Green energy options','Competitive rates','Simple plans'], true, false, '1-888-746-4702'),
  ('North American Power', 'north-american-power', 'Retail electricity provider serving residential customers across multiple Northeast and Midwest states with competitive rates.', '', 'https://www.napower.com', '', ARRAY['CT','NY','NJ','PA','IL','OH','MD','MA','RI'], ARRAY['residential'], 3.4, 1500, ARRAY['Multi-state coverage','Competitive rates','Online management','Simple enrollment'], true, false, '1-888-313-1391'),
  ('Viridian Energy', 'viridian-energy', 'Green energy provider offering 100% renewable electricity plans across multiple deregulated states through a direct sales model.', '', 'https://www.viridian.com', '', ARRAY['CT','NY','NJ','PA','IL','OH','MD','MA','RI','DE','ME'], ARRAY['residential','renewable'], 3.6, 1200, ARRAY['100% renewable','Multi-state coverage','Direct sales model','Green energy'], true, false, '1-888-998-2474'),
  ('Public Power', 'public-power', 'Multi-state retail electricity provider offering competitive rates and simple plans for residential customers across the Northeast.', '', 'https://www.publicpower.com', '', ARRAY['CT','MA','NY','NJ','PA','OH','IL','MD','RI','DE','ME'], ARRAY['residential'], 3.5, 2000, ARRAY['Multi-state coverage','Simple plans','Competitive rates','No deposit'], true, false, '1-888-564-5554'),
  ('Town Square Energy', 'town-square-energy', 'Retail electricity supplier serving residential and small business customers across multiple deregulated states in the Northeast and Midwest.', '', 'https://www.townsquareenergy.com', '', ARRAY['NY','NJ','PA','CT','MA','RI','OH','IL','MD','ME','DE'], ARRAY['residential','business'], 3.4, 900, ARRAY['Multi-state coverage','Simple plans','Competitive rates','Small business options'], true, false, '1-888-694-4267'),
  ('IDT Energy', 'idt-energy', 'New York-based retail energy provider offering electricity and natural gas to residential customers in the Northeast.', '', 'https://www.idtenergy.com', '', ARRAY['NY','NJ','PA','MD'], ARRAY['residential'], 3.3, 1600, ARRAY['Northeast coverage','Natural gas options','Variable rates','Online management'], true, false, '1-877-887-6866'),
  ('Residents Energy', 'residents-energy', 'Retail electricity provider focused on serving residential customers in the Northeast and Mid-Atlantic states.', '', 'https://www.residentsenergy.com', '', ARRAY['NY','NJ','PA','OH','MD'], ARRAY['residential'], 3.4, 800, ARRAY['Northeast coverage','Residential focus','Competitive rates','Simple plans'], true, false, '1-888-578-3750'),
  ('AEP Energy', 'aep-energy', 'Competitive retail electricity supplier backed by American Electric Power, serving customers in Ohio, Pennsylvania, and other deregulated states.', '', 'https://www.aepenergy.com', '', ARRAY['OH','PA','IL','NJ','MD','CT'], ARRAY['residential','business'], 4.0, 3500, ARRAY['Utility-backed','Multi-state coverage','Fixed rate plans','Business solutions'], true, false, '1-866-258-3782'),
  ('IGS Energy', 'igs-energy', 'Ohio-based retail energy provider offering electricity and natural gas plans with a focus on renewable energy and home services.', '', 'https://www.igsenergy.com', '', ARRAY['OH','PA','IL','MD'], ARRAY['residential','business','renewable'], 4.1, 2900, ARRAY['Renewable options','Home services','Natural gas','Ohio-based'], true, false, '1-800-280-4474'),
  ('Eligo Energy', 'eligo-energy', 'Retail electricity provider serving Illinois, Ohio, Pennsylvania, and New Jersey with competitive rates and an affiliate program.', '', 'https://www.eligoenergy.com', 'https://www.eligoenergy.com/affiliates', ARRAY['IL','OH','PA','NJ'], ARRAY['residential','business'], 4.0, 1400, ARRAY['Affiliate program','Multi-state coverage','Competitive rates','Simple enrollment'], true, true, '1-888-354-4687'),
  ('MC Squared Energy', 'mc-squared-energy', 'Illinois-based retail electricity provider offering competitive fixed and variable rate plans for residential and commercial customers.', '', 'https://www.mc2energy.com', '', ARRAY['IL'], ARRAY['residential','business'], 3.9, 1100, ARRAY['Illinois-focused','Competitive rates','Fixed rate plans','Business solutions'], true, false, '1-866-622-7697'),

-- ─── NORTHEAST PROVIDERS ────────────────────────────────────

  ('Liberty Power', 'liberty-power', 'National retail electricity provider serving residential and commercial customers across multiple deregulated states with competitive rates.', '', 'https://www.libertypowercorp.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA','CT'], ARRAY['residential','business'], 3.7, 2200, ARRAY['Multi-state coverage','Business solutions','Competitive rates','Online management'], true, false, '1-888-874-1517'),
  ('Agway Energy', 'agway-energy', 'Northeast energy provider offering electricity and natural gas plans with home protection services for residential customers.', '', 'https://www.agwayenergy.com', '', ARRAY['NY','PA','MD'], ARRAY['residential'], 3.8, 1000, ARRAY['Home protection','Northeast coverage','Natural gas','Residential focus'], true, false, '1-877-424-9291'),
  ('New Wave Energy', 'new-wave-energy', 'Licensed retail electricity and natural gas provider serving customers across multiple deregulated states in the Northeast and Midwest.', '', 'https://newwaveenergy.com', '', ARRAY['NY','NJ','PA','OH','IL','MD'], ARRAY['residential','business'], 3.5, 700, ARRAY['Multi-state coverage','Natural gas','Competitive rates','Business solutions'], true, false, '1-877-300-6747'),
  ('Verde Energy', 'verde-energy', 'Part of the Spark Energy family, offering 100% renewable electricity plans across multiple deregulated states.', '', 'https://www.verdeenergy.com', '', ARRAY['TX','PA','OH','IL','NY','NJ','MD','MA','CT'], ARRAY['residential','renewable'], 3.6, 1300, ARRAY['100% renewable','Multi-state coverage','Green energy','Spark Energy family'], true, false, '1-877-547-7275'),
  ('Provider Power', 'provider-power', 'Part of the Spark Energy family, serving residential customers in New England with competitive electricity and natural gas rates.', '', 'https://www.providerpower.com', '', ARRAY['MA','CT','RI','ME'], ARRAY['residential'], 3.5, 600, ARRAY['New England focus','Natural gas','Competitive rates','Spark Energy family'], true, false, '1-877-547-7275'),
  ('Constellation NewEnergy', 'constellation-newenergy', 'The commercial and industrial division of Constellation Energy, providing customized energy solutions for businesses.', '', 'https://www.constellation.com/business', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA','CT'], ARRAY['business'], 4.3, 4500, ARRAY['Business focus','Custom solutions','Multi-state coverage','Demand response'], true, false, '1-888-999-0499'),

-- ─── STATE-SPECIFIC PROVIDERS ───────────────────────────────

  ('Crius Energy', 'crius-energy', 'Multi-brand retail energy company operating across multiple deregulated states through various brand names.', '', 'https://www.criusenergy.com', '', ARRAY['CT','NY','NJ','PA','IL','OH','MD','MA','RI','DE','ME'], ARRAY['residential','business'], 3.5, 1800, ARRAY['Multi-brand','Multi-state coverage','Competitive rates','Various plan options'], true, false, ''),
  ('Just Energy', 'just-energy', 'International retail energy provider offering electricity and natural gas plans with green energy options across multiple markets.', '', 'https://www.justenergy.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA','CT','DE'], ARRAY['residential','business','renewable'], 3.4, 3200, ARRAY['International provider','Green energy','Multi-state coverage','Natural gas'], true, false, '1-866-587-8674'),
  ('Xoom Energy', 'xoom-energy', 'Retail electricity and natural gas provider serving residential and commercial customers across multiple deregulated states.', '', 'https://www.xoomenergy.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD','MA','CT','DE','RI'], ARRAY['residential','business'], 3.6, 1500, ARRAY['Multi-state coverage','Natural gas','Competitive rates','Online management'], true, false, '1-888-997-8979'),
  ('Starion Energy', 'starion-energy', 'Retail electricity supplier serving residential and commercial customers in the Northeast and Midwest with competitive rates.', '', 'https://www.starionenergy.com', '', ARRAY['CT','IL','MD','MA','NJ','NY','OH','PA','RI','DE'], ARRAY['residential','business'], 3.5, 1100, ARRAY['Multi-state coverage','Competitive rates','Fixed rate plans','Business solutions'], true, false, '1-800-600-3040'),
  ('SmartEnergy', 'smartenergy', 'Retail electricity provider offering competitive rates and renewable energy options in the Mid-Atlantic and Northeast regions.', '', 'https://www.smartenergy.com', '', ARRAY['MD','PA','NJ','NY','CT','MA','OH','IL','DE','RI'], ARRAY['residential','renewable'], 3.7, 800, ARRAY['Renewable options','Northeast coverage','Competitive rates','Smart solutions'], true, false, '1-888-557-6278'),
  ('Palmco Power', 'palmco-power', 'Retail electricity and natural gas provider serving residential customers in the Northeast and Mid-Atlantic states.', '', 'https://www.palmcoenergy.com', '', ARRAY['NY','NJ','PA','MD','CT','MA','OH','IL'], ARRAY['residential'], 3.3, 1400, ARRAY['Northeast coverage','Natural gas','Variable rates','Residential focus'], true, false, '1-877-574-1445'),
  ('SFE Energy', 'sfe-energy', 'Retail energy provider offering electricity and natural gas through door-to-door sales in multiple deregulated states.', '', 'https://www.sfeenergy.com', '', ARRAY['NY','NJ','PA','MD','CT','MA','OH','IL'], ARRAY['residential'], 3.2, 900, ARRAY['Multi-state coverage','Natural gas','Door-to-door sales','Residential focus'], true, false, '1-877-316-8777'),
  ('Infinite Energy', 'infinite-energy', 'Retail energy provider offering electricity and natural gas plans with a focus on customer service and competitive pricing.', '', 'https://www.infiniteenergy.com', '', ARRAY['TX','NJ','OH','PA'], ARRAY['residential','business'], 4.0, 2100, ARRAY['Customer service focus','Competitive pricing','Multi-state coverage','Business solutions'], true, false, '1-855-564-4633'),
  ('Tomorrow Energy', 'tomorrow-energy', 'Clean energy provider offering 100% renewable electricity plans across multiple deregulated states with carbon offset options.', '', 'https://www.tomorrowenergy.com', '', ARRAY['OH','PA','IL','NY','NJ','MD','MA','CT'], ARRAY['residential','renewable'], 4.2, 600, ARRAY['100% renewable','Carbon offsets','Multi-state coverage','Clean energy'], true, false, '1-855-894-2797'),
  ('CleanChoice Energy', 'cleanchoice-energy', 'Renewable energy provider offering 100% wind and solar electricity plans in multiple deregulated states with no installation required.', '', 'https://www.cleanchoiceenergy.com', '', ARRAY['NY','NJ','PA','MD','MA','CT','OH','IL','DE','RI'], ARRAY['residential','renewable'], 4.3, 1000, ARRAY['100% wind & solar','No installation','Multi-state coverage','Green energy'], true, false, '1-800-218-3220'),
  ('Arcadia', 'arcadia', 'Clean energy platform connecting customers to renewable energy sources through community solar and wind energy programs.', '', 'https://www.arcadia.com', '', ARRAY['NY','NJ','PA','MD','MA','CT','OH','IL','DE','RI','ME'], ARRAY['residential','renewable'], 4.4, 1500, ARRAY['Community solar','Wind energy','No installation','Clean energy platform'], true, false, ''),
  ('Think Energy', 'think-energy', 'Retail electricity provider offering competitive rates and green energy options for residential and commercial customers.', '', 'https://www.thinkenergy.com', '', ARRAY['TX','IL','OH','PA','NY','NJ','MD'], ARRAY['residential','business','renewable'], 3.8, 700, ARRAY['Green energy options','Multi-state coverage','Competitive rates','Business solutions'], true, false, '1-888-923-3637')

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  logo_url = EXCLUDED.logo_url,
  website_url = EXCLUDED.website_url,
  affiliate_url = EXCLUDED.affiliate_url,
  supported_states = EXCLUDED.supported_states,
  offer_categories = EXCLUDED.offer_categories,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  features = EXCLUDED.features,
  has_affiliate_program = EXCLUDED.has_affiliate_program,
  phone = EXCLUDED.phone,
  updated_at = now();

-- ============================================================
-- SEED COMPLETE: 50 providers across 12 deregulated states
-- ============================================================
